server:
  port: 8080

logging:
  level:
    com:
      wazzups:
        itauunibancotransaction: debug

stats:
  seconds: 65

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always